Building font page
mugberto/newsweek-clone pull request #1
Opened 2020-05-08 07:25 UTC by mugberto

2020-05-16 19:13 UTC, lucasmazo32 requested changes
# Changes required :wrench:

Great job. This page has many details and you almost copied it as it is. You need to make two small changes before the project gets approved. Please check the comments below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-16 19:13 UTC, lucasmazo32 commented on index.html
> +                />
- [ ] The size of this articles are not the same as the original page. Kindly fix that.

> Original
![image](https://user-images.githubusercontent.com/57414789/82128187-d2692100-977e-11ea-90f3-98a67d8d0649.png)
> Your page
![image](https://user-images.githubusercontent.com/57414789/82128191-ddbc4c80-977e-11ea-9185-d8b21e748813.png)

2020-05-16 19:13 UTC, lucasmazo32 commented on index.html
> +          <div class="row mx-md-0">
- [ ] I am missing the sign up section. Please add it!

> ![image](https://user-images.githubusercontent.com/57414789/82128235-2e33aa00-977f-11ea-915b-e86d3560cf29.png)

2020-05-18 00:04 UTC, mugberto commented
> # Changes required 
> Great job. This page has many details and you almost copied it as it is. You need to make two small changes before the project gets approved. Please check the comments below.
> 
> ### Happy coding! 
> ## Lucas Mazo

Thank you for the review. I have fixed the issues.

2020-05-18 23:41 UTC, christianotieno requested changes
Hello @mugberto 👋 
##
## The [page](https://raw.githack.com/mugberto/newsweek-clone/building-font-page/index.html) is very responsive and shows good use of bootstrap.

For this project, however, we have to make sure nothing is messed up. Good job implementing the above changes.
-  The markup is required to not have any errors. Please validate it with this [tool](https://validator.w3.org/nu/#textarea) and fix the emerging errors. Thank you.

Make this change and then submit another code review. hank you.

2020-05-19 08:00 UTC, mugberto commented
> Hello @mugberto 
> 
> ## The [page](https://raw.githack.com/mugberto/newsweek-clone/building-font-page/index.html) is very responsive and shows good use of bootstrap.
> For this project, however, we have to make sure nothing is messed up. Good job implementing the above changes.
> 
> * The markup is required to not have any errors. Please validate it with this [tool](https://validator.w3.org/nu/#textarea) and fix the emerging errors. Thank you.
> 
> Make this change and then submit another code review. hank you.

 I introduced these errors when I was fixing issues raised in the previous feedback. Thank you @christianotieno. I have taken notes. I will always validate before the submission.

2020-05-20 00:25 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @mugberto! :+1:
- You can now merge to master. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-05-20 08:19 UTC, merged